In [125]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict, KFold
from sklearn import linear_model
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_squared_error, mean_absolute_error
from scipy.stats import pearsonr
import scipy.stats as stats
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import spearmanr
from numpy import cov

In [126]:
data = pd.read_csv(r'C:/Users/lenovo/Desktop/g2 task/heart.csv' )
dataset=data.to_numpy()
class_target=dataset[:,-1]
class_instances=dataset[:,:-1]
class_instances=stats.zscore(class_instances, axis=0)

In [127]:
X_train, X_test, Y_train, Y_test = train_test_split(class_instances,class_target, test_size = 0.3 ,random_state = 35)

In [128]:
standarddev_train=np.std(X_train)
averagetrain=np.average(X_train)
X_train=(X_train - np.average(X_train)) / (np.std(X_train))
X_test=(X_test - averagetrain) / standarddev_train

In [129]:
#Lasso Regression
alpha_value = 0.1  

reg_lasso = linear_model.Lasso(alpha=alpha_value)
reg_lasso = reg_lasso.fit(X_train, Y_train).predict(X_test)
lasso_predict=reg_lasso.reshape(1,-1)
print("lasso predict list")
print(lasso_predict)
lasso_predict.shape

#Ridge Regression
reg_Ridge = linear_model.Ridge(alpha=.5)
reg_Ridge = reg_Ridge.fit(X_train, Y_train).predict(X_test)
Ridge_predict=reg_Ridge.reshape(1,-1)
print("Ridge_predict list")
print(Ridge_predict)
Ridge_predict.shape

#LogisticRegression
LogisticRegression = linear_model.LogisticRegression(penalty='l2')
LogisticRegression = LogisticRegression.fit(X_train, Y_train).predict(X_test)
Logistic_predict=LogisticRegression.reshape(1,-1)
print("Logistic_predict list")
print(Logistic_predict)
Logistic_predict.shape

lasso predict list
[[0.76360943 0.19084147 0.29537977 0.54900856 0.45258558 0.60646431
  0.63531354 0.20136595 0.56341025 0.61131406 0.64208471 0.45464502
  0.54176307 0.7933636  0.48990129 0.52358563 0.24013998 0.65528658
  0.27826924 0.58433825 0.35796963 0.19084147 0.63937462 0.76813944
  0.21839481 0.13904603 0.68016618 0.56368947 0.61760262 0.29379879
  0.23505345 0.29379879 0.44565128 0.37587591 0.10026273 0.35392591
  0.57827159 0.03221149 0.58906411 0.59604544 0.47752418 0.63771026
  0.36879654 0.34864572 0.63975893 0.31616194 0.71962837 0.45537905
  0.63975893 0.76767439 0.64483649 0.52988148 0.58929308 0.55180525
  0.55878975 0.44479823 0.56638491 0.5761973  0.41787315 0.66354044
  0.37850067 0.88721798 0.61781967 0.4679098  0.15616583 0.68847904
  0.24013998 0.72412331 0.57701617 0.14334512 0.77853052 0.57619413
  0.68847904 0.52988148 0.53137199 0.15616583 0.53559842 0.37685553
  0.4955814  0.61165645 0.77853052 0.5761973  0.27287079 0.32209395
  0.52449842 0.77003816 0.558

(1, 308)

In [130]:
classificationlasso_list=[]

classificationlasso_list = np.where(lasso_predict > 0.5, 1, 0)
print("Lasso regression to classification list")
print(classificationlasso_list)


classificationRidge_list=[]
classificationRidge_list = np.where(Ridge_predict > 0.5, 1, 0)
print("Ridge regression to classification list")
print(classificationRidge_list)
        

Lasso regression to classification list
[[1 0 0 1 0 1 1 0 1 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0
  1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 0 0 1 0 1 1 0 1 1
  1 1 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0
  1 0 0 0 1 1 0 1 0 1 1 1 0 0 0 1 0 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 0 1 0 0
  0 1 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1
  1 0 1 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 0
  1 1 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 1 0 1 0 1 1 0 0
  0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 1 0 1 0 1 1 1 1 0 1 0 1 0 1 1 1 1 1 0 0
  1 1 1 1 0 1 0 1 0 1 1 1 0 1 0 0 1 1 0 1]]
Ridge regression to classification list
[[1 0 0 1 0 1 1 0 1 1 1 0 0 1 1 1 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0
  0 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 0 1 0 1 1 0 1 1
  1 1 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0
  1 0 0 0 1 1 1 1 0 1 1 1 0 0 0 1 0 1 0 1 1 1 1 0 1 1 1 1 1 1 

In [131]:
kf = KFold(n_splits=5)  # Define number of folds for k-fold cross validation
for train_index, test_index in kf.split(class_instances):
    X_train_kfold, X_test_kfold = class_instances[train_index], class_instances[test_index]
    Y_train_kfold, Y_test_kfold = class_target[train_index], class_target[test_index]
    reg_lasso_kfold = linear_model.Lasso(alpha=alpha_value)
    reg_lasso_kfold.fit(X_train_kfold, Y_train_kfold)
    reg_lasso_predict_kfold = reg_lasso_kfold.predict(X_test_kfold)
    
    
    reg_Ridge_kfold = linear_model.Ridge(alpha=.5)
    reg_Ridge_kfold.fit(X_train_kfold, Y_train_kfold)
    reg_Ridge_predict_kfold = reg_lasso_kfold.predict(X_test_kfold)

In [132]:
print(" reg_lasso_predict_kfold predict list")
print(reg_lasso_predict_kfold)
reg_lasso_predict_kfold.shape

print("reg_Ridge_predict_kfold list")
print(reg_Ridge_predict_kfold)
reg_Ridge_predict_kfold.shape

 reg_lasso_predict_kfold predict list
[0.27362526 0.33987506 0.31107474 0.5339687  0.19646449 0.79875432
 0.72553541 0.61718131 0.65829863 0.20627132 0.55172812 0.38481917
 0.58673213 0.0770323  0.3799899  0.49081307 0.63274403 0.68280275
 0.53179852 0.54734069 0.26285302 0.59644885 0.5309308  0.75376056
 0.41497741 0.27875416 0.59644885 0.19646449 0.79979213 0.41628669
 0.57415499 0.60298973 0.41628669 0.17035008 0.71539133 0.6266445
 0.61748913 0.57107773 0.61748913 0.40136745 0.54861558 0.73967219
 0.76601217 0.42218198 0.75376056 0.82106538 0.77678122 0.65843414
 0.68670768 0.65965652 0.72970137 0.78208251 0.73746626 0.59280949
 0.75376056 0.18639012 0.27362526 0.77564589 0.35329981 0.63727737
 0.47844203 0.62808654 0.27056769 0.54506601 0.26285302 0.29464406
 0.18588002 0.39786513 0.35117663 0.22091837 0.28846189 0.52513638
 0.20409569 0.51481585 0.40136745 0.51491293 0.52649766 0.57452892
 0.53337808 0.53623052 0.54992731 0.53337808 0.33987506 0.56644079
 0.66196833 0.22038999 0.

(205,)

In [133]:
classificationlassokfold_list=[]

classificationlassokfold_list = np.where(reg_lasso_predict_kfold > 0.5, 1, 0)
print("Lasso regression to classificationlassokfold_list list")
print(classificationlassokfold_list)


classificationRidgekfold_list=[]
classificationRidgekfold_list = np.where(reg_Ridge_predict_kfold > 0.5, 1, 0)
print("Ridge regression to classificationlassokfold_list list")
print(classificationlassokfold_list)

Lasso regression to classificationlassokfold_list list
[0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 0 1 1 1 1 0 1 1 1 0 0 1 0 1 0 1 1 0 0 1 1 1
 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 1
 0 1 1 1 1 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0
 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 1
 0 1 1 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 1
 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 0]
Ridge regression to classificationlassokfold_list list
[0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 0 1 1 1 1 0 1 1 1 0 0 1 0 1 0 1 1 0 0 1 1 1
 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 1
 0 1 1 1 1 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0
 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 1
 0 1 1 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 1
 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 0]


In [134]:
re_Ytest=Y_test.reshape(1,-1)
print("lable list")
print(re_Ytest)
re_Ytest.shape

lable list
[[1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1.
  0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0.
  1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1.
  1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1.
  0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1.
  0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0.
  0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1.
  1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0.
  1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0.
  0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0.
  0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0.
  1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0.
  1. 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1.]]


(1, 308)

In [135]:
    # Lasso regression MAE و RMSE
    mae = mean_absolute_error(re_Ytest, lasso_predict)
    rmse = np.sqrt(mean_squared_error(re_Ytest, lasso_predict))
    print('MAE: %.3f' % mae)
    print('RMSE: %.3f' % rmse)
    
    covariance = cov(re_Ytest, lasso_predict)
    print('covariance')
    print(covariance)
    # ارزیابی همبستگی
    corr, _ = spearmanr(re_Ytest, lasso_predict)
    
    print('Spearmans correlation: %.3f' % corr)
    


MAE: 0.378
RMSE: 0.400
covariance
[[0.25029612 0.06108231]
 [0.06108231 0.03188722]]
Spearmans correlation: nan


In [136]:
    # Ridge regression MAE و RMSE
    mae = mean_absolute_error(re_Ytest, Ridge_predict)
    rmse = np.sqrt(mean_squared_error(re_Ytest, Ridge_predict))
    print('MAE: %.3f' % mae)
    print('RMSE: %.3f' % rmse)
    
    covariance = cov(re_Ytest, Ridge_predict)
    print('covariance')
    print(covariance)
    # ارزیابی همبستگی
    corr, _ = spearmanr(re_Ytest, Ridge_predict)
    
    print('Spearmans correlation: %.3f' % corr)

MAE: 0.291
RMSE: 0.360
covariance
[[0.25029612 0.12764771]
 [0.12764771 0.13502075]]
Spearmans correlation: nan


In [137]:
    # logestic regression MAE و RMSE
    mae = mean_absolute_error(re_Ytest, Logistic_predict)
    rmse = np.sqrt(mean_squared_error(re_Ytest, Logistic_predict))
    print('MAE: %.3f' % mae)
    print('RMSE: %.3f' % rmse)
    
    covariance = cov(re_Ytest, Logistic_predict)
    print('covariance')
    print(covariance)
    # ارزیابی همبستگی
    corr, _ = spearmanr(re_Ytest, Logistic_predict)
    
    print('Spearmans correlation: %.3f' % corr)

MAE: 0.172
RMSE: 0.415
covariance
[[0.25029612 0.16316257]
 [0.16316257 0.24738779]]
Spearmans correlation: nan
